version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: ["start-dev", "--import-realm"]
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./realm-config:/opt/keycloak/data/import

  postgres:
    image: postgres:16.2
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"

  api:
    build: ./api
    container_name: api-1
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      Keycloak__Authority: http://keycloak:8080/realms/myrealm
      Keycloak__Audience: account
      ConnectionStrings__Redis: redis:6379
    ports:
      - "8001:80"
    depends_on:
      - keycloak
      - postgres
      - redis

  api2:
    build: ./api
    container_name: api-2
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      Keycloak__Authority: http://keycloak:8080/realms/myrealm
      Keycloak__Audience: account
      ConnectionStrings__Redis: redis:6379
    ports:
      - "8002:80"
    depends_on:
      - keycloak
      - postgres
      - redis

  app:
    build:
      context: ./app/signalr-app
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "5173:3000"
    depends_on:
      - api

volumes:
  postgres_data: